# K-Fold Cross validation for consistent training n test data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

In [11]:
digits = load_digits()
from sklearn.model_selection import train_test_split
xt,xtt,yt,ytt = train_test_split(digits.data,digits.target,test_size= 0.2)

In [12]:
lr = LogisticRegression()
lr.fit(xt,yt)
lr.score(xtt,ytt)

C:\Users\Desktop\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.95

In [13]:
#svm
s = SVC()
s.fit(xt,yt)
s.score(xtt,ytt)

0.9944444444444445

In [14]:
#randomforest
rf = RandomForestClassifier()
rf.fit(xt,yt)
rf.score(xtt,ytt)

0.975

In [16]:
from sklearn.model_selection import KFold
kf = KFold(n_splits =3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [21]:
for train,test in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train,test)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [22]:
def get_score(model,xt,xtt,yt,ytt):
    model.fit(xt,yt)
    return model.score(xtt,ytt)

In [23]:
get_score(LogisticRegression(),xt,xtt,yt,ytt)

C:\Users\Desktop\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.95

In [24]:
get_score(SVC(),xt,xtt,yt,ytt)

0.9944444444444445

In [25]:
get_score(RandomForestClassifier(),xt,xtt,yt,ytt)

0.975

In [27]:
#stratifies_KFold
from sklearn .model_selection import StratifiedKFold
f = StratifiedKFold()

In [37]:
scores_lr = []
scores_svm = []
scores_rf = []

In [38]:
for train,test in kf.split(digits.data):
    xt,xtt,yt,ytt=digits.data[train],digits.data[test],digits.target[train],digits.target[test] 
    print(get_score(LogisticRegression(),xt,xtt,yt,ytt))
    print(get_score(SVC(),xt,xtt,yt,ytt))
    print(get_score(RandomForestClassifier(),xt,xtt,yt,ytt))

C:\Users\Desktop\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9232053422370617
0.9666110183639399
0.9415692821368948


C:\Users\Desktop\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9415692821368948
0.9816360601001669
0.9582637729549248


C:\Users\Desktop\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9148580968280468
0.9549248747913188
0.9215358931552587


In [40]:
scores_lr.append(get_score(LogisticRegression(solver = 'liblinear', multi_class = 'ovr'),xt,xtt,yt,ytt))
scores_svm.append(get_score(SVC(),xt,xtt,yt,ytt))
scores_rf.append(get_score(RandomForestClassifier(),xt,xtt,yt,ytt))

In [44]:
scores_lr

[0.9115191986644408]

In [45]:
scores_svm

[0.9549248747913188]

In [46]:
scores_rf

[0.9315525876460768]

## cross-val-score

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [3]:
from sklearn.datasets import load_digits
d = load_digits()

In [4]:
from sklearn.model_selection import cross_val_score

In [6]:
cross_val_score(LogisticRegression(solver ='liblinear',multi_class ='ovr'),d.data,d.target,cv =3)

array([0.89482471, 0.95325543, 0.90984975])

In [8]:
cross_val_score(SVC(gamma='auto'), d.data, d.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [9]:
cross_val_score(RandomForestClassifier(n_estimators=40),d.data, d.target,cv=3)

array([0.92654424, 0.94991653, 0.92153589])

In [11]:
s1 =cross_val_score(RandomForestClassifier(),d.data,d.target,cv = 10)
np.average(s1)

0.9454593420235877

In [14]:
s2 = cross_val_score(RandomForestClassifier(n_estimators =10),d.data,d.target,cv =10)
np.average(s2)

0.9098572315332092

In [15]:
s3 = cross_val_score(RandomForestClassifier(n_estimators =20),d.data,d.target,cv =10)
np.average(s3)

0.9293109869646183

In [16]:
s4 = cross_val_score(RandomForestClassifier(n_estimators =30),d.data,d.target,cv =10)
np.average(s4)

0.9449068901303537

In [17]:
s5 = cross_val_score(RandomForestClassifier(n_estimators =40),d.data,d.target,cv =10)
np.average(s5)

0.947135319677219

In [18]:
s6 = cross_val_score(RandomForestClassifier(n_estimators =50),d.data,d.target,cv =10)
np.average(s6)

0.9504562383612661

In [19]:
s7 = cross_val_score(RandomForestClassifier(n_estimators =60),d.data,d.target,cv =10)
np.average(s7)

0.9482309124767225

In [22]:
from sklearn.datasets import load_iris
i = load_iris()

In [23]:
dir(i)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [63]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
cross_val_score(LogisticRegression(solver = 'liblinear',multi_class ='ovr'),i.data,i.target,cv=3)

array([0.96, 0.96, 0.94])

In [37]:
cross_val_score(SVC(gamma='auto'),i.data,i.target,cv=3)

array([0.98, 0.98, 0.96])

In [56]:
cross_val_score(RandomForestClassifier(n_estimators = 50),i.data,i.target,cv=3)

array([0.98, 0.94, 0.98])

In [64]:
cross_val_score(DecisionTreeClassifier(),i.data,i.target,cv=3)

array([0.98, 0.94, 1.  ])